In [2]:
import pandas as pd
import numpy as np

In [3]:
customers = pd.read_excel("../data/raw/Dataset1_Customers.xlsx")
transactions = pd.read_excel("../data/raw/Dataset2_Transactions.xlsx")
wallet = pd.read_excel("../data/raw/Dataset3_Wallet.xlsx")
sessions = pd.read_excel("../data/raw/Dataset4_Sessions.xlsx")
campaigns = pd.read_excel("../data/raw/Dataset5_Campaigns.xlsx")

In [4]:
print("Customers:", customers.shape)
print("Transactions:", transactions.shape)
print("Wallet:", wallet.shape)
print("Sessions:", sessions.shape)
print("Campaigns:", campaigns.shape)

Customers: (25000, 6)
Transactions: (25000, 6)
Wallet: (25000, 4)
Sessions: (25000, 4)
Campaigns: (25000, 5)

In [5]:
print("Customers:")
print(customers.columns.tolist())

print("\nTransactions:")
print(transactions.columns.tolist())

print("\nWallet:")
print(wallet.columns.tolist())

print("\nSessions:")
print(sessions.columns.tolist())

print("\nCampaigns:")
print(campaigns.columns.tolist())

Customers:
['Customer_ID', 'Age', 'City', 'State', 'Income_Bracket', 'Registration_Year']

Transactions:
['Transaction_ID', 'Customer_ID', 'Brand', 'Purchase_Amount', 'Cashback', 'Payment_Method']

Wallet:
['Wallet_ID', 'Customer_ID', 'Earned_Points', 'Redeemed_Points']

Sessions:
['Session_ID', 'Customer_ID', 'Pages_Visited', 'Converted']

Campaigns:
['Campaign_ID', 'Brand', 'Impressions', 'Clicks', 'Revenue']

In [6]:
# ==========================================
# FEATURE ENGINEERING
# IDENTIFY AVAILABLE FEATURES
# ==========================================

print("CUSTOMERS")
print(customers.columns.tolist())

print("\nTRANSACTIONS")
print(transactions.columns.tolist())

print("\nWALLET")
print(wallet.columns.tolist())

print("\nSESSIONS")
print(sessions.columns.tolist())

print("\nCAMPAIGNS")
print(campaigns.columns.tolist())

CUSTOMERS
['Customer_ID', 'Age', 'City', 'State', 'Income_Bracket', 'Registration_Year']

TRANSACTIONS
['Transaction_ID', 'Customer_ID', 'Brand', 'Purchase_Amount', 'Cashback', 'Payment_Method']

WALLET
['Wallet_ID', 'Customer_ID', 'Earned_Points', 'Redeemed_Points']

SESSIONS
['Session_ID', 'Customer_ID', 'Pages_Visited', 'Converted']

CAMPAIGNS
['Campaign_ID', 'Brand', 'Impressions', 'Clicks', 'Revenue']

In [7]:
print(
    "Customers IDs in Transactions:",
    transactions['Customer_ID'].isin(customers['Customer_ID']).sum()
)

Customers IDs in Transactions: 25000

In [8]:
# ==========================================
# CUSTOMER TRANSACTION FEATURES
# ==========================================

transaction_features = transactions.groupby('Customer_ID').agg(
    total_transactions=('Transaction_ID', 'count'),
    total_spent=('Purchase_Amount', 'sum'),
    average_purchase=('Purchase_Amount', 'mean')
).reset_index()

transaction_features.head()

  Customer_ID  total_transactions  total_spent  average_purchase
0     C100001                   1         3288            3288.0
1     C100003                   1         2048            2048.0
2     C100004                   1          234             234.0
3     C100005                   3        10266            3422.0
4     C100007                   1         7037            7037.0

In [9]:
transaction_features.shape

(15818, 4)

In [10]:
transaction_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15818 entries, 0 to 15817
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         15818 non-null  object
 1   total_transactions  15818 non-null  int64
 2   total_spent         15818 non-null  int64
 3   average_purchase    15818 non-null  float64
dtypes: float64(1), int64(2), object(1)
memory usage: 494.4+ KB

In [11]:
transaction_features.isnull().sum()

Customer_ID           0
total_transactions    0
total_spent           0
average_purchase      0
dtype: int64

In [12]:
# ==========================================
# CUSTOMER SESSION FEATURES
# ==========================================

session_features = sessions.groupby('Customer_ID').agg(
    total_sessions=('Session_ID', 'count'),
    total_pages_visited=('Pages_Visited', 'sum')
).reset_index()

session_features.head()

  Customer_ID  total_sessions  total_pages_visited
0     C100000               2                   36
1     C100001               1                   11
2     C100002               2                   32
3     C100003               1                   12
4     C100004               1                   13

In [13]:
session_features.shape

(15765, 3)

In [14]:
session_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15765 entries, 0 to 15764
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          15765 non-null  object
 1   total_sessions       15765 non-null  int64
 2   total_pages_visited  15765 non-null  int64
dtypes: int64(2), object(1)
memory usage: 369.6+ KB

In [15]:
session_features.isnull().sum()

Customer_ID            0
total_sessions         0
total_pages_visited    0
dtype: int64

In [16]:
# ==========================================
# CUSTOMER WALLET FEATURES
# ==========================================

wallet_features = wallet.groupby('Customer_ID').agg(
    total_earned_points=('Earned_Points', 'sum'),
    total_redeemed_points=('Redeemed_Points', 'sum')
).reset_index()

wallet_features.head()

  Customer_ID  total_earned_points  total_redeemed_points
0     C100000                   85                    395
1     C100001                 1324                    522
2     C100003                 2399                    676
3     C100004                 1350                    595
4     C100005                  734                    208

In [17]:
wallet_features.shape

(15821, 3)

In [18]:
wallet_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15821 entries, 0 to 15820
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            15821 non-null  object
 1   total_earned_points    15821 non-null  int64
 2   total_redeemed_points  15821 non-null  int64
dtypes: int64(2), object(1)
memory usage: 370.9+ KB

In [19]:
wallet_features.isnull().sum()

Customer_ID              0
total_earned_points      0
total_redeemed_points    0
dtype: int64

In [20]:
campaigns.columns.tolist()

['Campaign_ID', 'Brand', 'Impressions', 'Clicks', 'Revenue']

In [21]:
# ==========================================
# COMBINE CUSTOMER FEATURES
# ==========================================

feature_data = customers.copy()

feature_data.head()

  Customer_ID  Age     City        State Income_Bracket  Registration_Year
0     C100000   56     Pune      Gujarat         Medium               2025
1     C100001   46   Nagpur  West Bengal            Low               2025
2     C100002   32  Kolkata    Rajasthan           High               2022
3     C100003   25   Nagpur    Karnataka           High               2025
4     C100004   38     Pune   Tamil Nadu         Medium               2022

In [22]:
feature_data = feature_data.merge(
    transaction_features,
    on='Customer_ID',
    how='left'
)

In [23]:
feature_data = feature_data.merge(
    session_features,
    on='Customer_ID',
    how='left'
)

In [24]:
feature_data = feature_data.merge(
    wallet_features,
    on='Customer_ID',
    how='left'
)

In [25]:
feature_data.shape

(25000, 13)

In [26]:
feature_data.head()

,Customer_ID,Age,City,State,Income_Bracket,Registration_Year,total_transactions,total_spent,average_purchase,total_sessions,total_pages_visited,total_earned_points,total_redeemed_points
0,C100000,56,Pune,Gujarat,Medium,2025,NaN,NaN,NaN,2.0,36.0,85.0,395.0
1,C100001,46,Nagpur,West Bengal,Low,2025,1.0,3288.0,3288.0,1.0,11.0,1324.0,522.0
2,C100002,32,Kolkata,Rajasthan,High,2022,NaN,NaN,NaN,2.0,32.0,NaN,NaN
3,C100003,25,Nagpur,Karnataka,High,2025,1.0,2048.0,2048.0,1.0,12.0,2399.0,676.0
4,C100004,38,Pune,Tamil Nadu,Medium,2022,1.0,234.0,234.0,1.0,13.0,1350.0,595.0

In [27]:
feature_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            25000 non-null  object
 1   Age                    25000 non-null  int64
 2   City                   25000 non-null  object
 3   State                  25000 non-null  object
 4   Income_Bracket         25000 non-null  object
 5   Registration_Year      25000 non-null  int64
 6   total_transactions     15818 non-null  float64
 7   total_spent            15818 non-null  float64
 8   average_purchase       15818 non-null  float64
 9   total_sessions         15765 non-null  float64
 10  total_pages_visited    15765 non-null  float64
 11  total_earned_points    15821 non-null  float64
 12  total_redeemed_points  15821 non-null  float64
dtypes: float64(7), int64(2), object(4)
memory usage: 2.5+ MB

In [28]:
feature_data.isnull().sum()

Customer_ID                 0
Age                         0
City                        0
State                       0
Income_Bracket              0
Registration_Year           0
total_transactions       9182
total_spent              9182
average_purchase         9182
total_sessions           9235
total_pages_visited      9235
total_earned_points      9179
total_redeemed_points    9179
dtype: int64

In [29]:
# ==========================================
# HANDLE MISSING VALUES
# ==========================================

feature_data.isnull().sum()

Customer_ID                 0
Age                         0
City                        0
State                       0
Income_Bracket              0
Registration_Year           0
total_transactions       9182
total_spent              9182
average_purchase         9182
total_sessions           9235
total_pages_visited      9235
total_earned_points      9179
total_redeemed_points    9179
dtype: int64

In [30]:
feature_data.isnull().sum()[feature_data.isnull().sum() > 0]

total_transactions       9182
total_spent              9182
average_purchase         9182
total_sessions           9235
total_pages_visited      9235
total_earned_points      9179
total_redeemed_points    9179
dtype: int64

In [31]:
feature_columns = [
    'total_transactions',
    'total_spent',
    'average_purchase',
    'total_sessions',
    'total_pages_visited',
    'total_earned_points',
    'total_redeemed_points'
]

feature_data[feature_columns] = feature_data[feature_columns].fillna(0)

In [32]:
feature_data[feature_columns].isnull().sum()

total_transactions       0
total_spent              0
average_purchase         0
total_sessions           0
total_pages_visited      0
total_earned_points      0
total_redeemed_points    0
dtype: int64

In [33]:
feature_data.head()

,Customer_ID,Age,City,State,Income_Bracket,Registration_Year,total_transactions,total_spent,average_purchase,total_sessions,total_pages_visited,total_earned_points,total_redeemed_points
0,C100000,56,Pune,Gujarat,Medium,2025,0.0,0.0,0.0,2.0,36.0,85.0,395.0
1,C100001,46,Nagpur,West Bengal,Low,2025,1.0,3288.0,3288.0,1.0,11.0,1324.0,522.0
2,C100002,32,Kolkata,Rajasthan,High,2022,0.0,0.0,0.0,2.0,32.0,0.0,0.0
3,C100003,25,Nagpur,Karnataka,High,2025,1.0,2048.0,2048.0,1.0,12.0,2399.0,676.0
4,C100004,38,Pune,Tamil Nadu,Medium,2022,1.0,234.0,234.0,1.0,13.0,1350.0,595.0

In [34]:
feature_data.shape

(25000, 13)

In [35]:
feature_data.isnull().sum()

Customer_ID              0
Age                      0
City                     0
State                    0
Income_Bracket           0
Registration_Year        0
total_transactions       0
total_spent              0
average_purchase         0
total_sessions           0
total_pages_visited      0
total_earned_points      0
total_redeemed_points    0
dtype: int64

In [36]:
# ==========================================
# SAVE PROCESSED FEATURE DATA
# ==========================================

feature_data.to_csv(
    "../data/processed/feature_data.csv",
    index=False
)

In [37]:
import os

os.path.exists("../data/processed/feature_data.csv")

True

In [38]:
feature_data_saved = pd.read_csv(
    "../data/processed/feature_data.csv"
)

feature_data_saved.head()

,Customer_ID,Age,City,State,Income_Bracket,Registration_Year,total_transactions,total_spent,average_purchase,total_sessions,total_pages_visited,total_earned_points,total_redeemed_points
0,C100000,56,Pune,Gujarat,Medium,2025,0.0,0.0,0.0,2.0,36.0,85.0,395.0
1,C100001,46,Nagpur,West Bengal,Low,2025,1.0,3288.0,3288.0,1.0,11.0,1324.0,522.0
2,C100002,32,Kolkata,Rajasthan,High,2022,0.0,0.0,0.0,2.0,32.0,0.0,0.0
3,C100003,25,Nagpur,Karnataka,High,2025,1.0,2048.0,2048.0,1.0,12.0,2399.0,676.0
4,C100004,38,Pune,Tamil Nadu,Medium,2022,1.0,234.0,234.0,1.0,13.0,1350.0,595.0

In [39]:
feature_data_saved.shape

(25000, 13)